ls:
  src:
    .dir: kebab-case
    .ts: regex:([\[\]_.a-z0-9]*)([-.][a-z0-9]+)*
    .tsx: regex:([\[\]_.a-zA-Z0-9]*)([-.][a-zA-Z0-9]+)*

ignore:
  - .git
  - node_modules
  - build
  - .vscode
  - .idea
