version: '3.9'
services:
  autoline_postgres:
    container_name: share_call_postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_local:/var/lib/postgresql/data
    env_file:
      - ../../.env

volumes:
  postgres_local:
    driver: local
